= Management VM
:toc:
:toclevels: 3

WARNING: This page is a work in progress.

. Copy the management VM image from `node-images` into the appropriate location.
+
[source,bash]
----
mkdir -p /vms/images
cp node-images/output-management-vm-qemu/management-vm-x86_64.qcow2 /vms/images/
----
. Copy the seed files, `meta-data`, `user-data`, and `network-config` into position
+
[source,code]
----
mkdir -p /vms/cloud-init/management-vm

ansible localhost -e @roles/node_images_hypervisor/defaults/main.yml -c local -m template -a "src=roles/node_images_hypervisor/templates/bootstrap/user-data.yml.j2 dest=user-data"

cp metal-provision/roles/node_images_hypervisor/files/bootstrap/meta-data /vms/cloud-init/management-vm/meta-data
cp metal-provision/roles/node_images_hypervisor/templates/bootstrap/user-data.yml.j2 /vms/cloud-init/management-vm/user-data
cp metal-provision/roles/node_images_hypervisor/files/bootstrap/network-config /vms/cloud-init/management-vm/network-config
----
. Generate an SSH key
+
[source,code]
----
ssh-keygen
----
. Use `yq` to update `user-data`
+
[source,code]
----
yq -i eval '(.users.[] | select(.name = "root") | .ssh_authorized_keys) += "'"$(cat /root/.ssh/id_rsa.pub)"'"' /vms/cloud-init/management-vm/user-data
----
. Create the cloud-init ISO
+
[source,bash]
----
xorriso -as genisoimage \
    -output ~/vms/cloud-init/management-vm/cloud-init.iso \
    -volid CIDATA -joliet -rock -f \
    ~/vms/cloud-init/management-vm/user-data \
    ~/vms/cloud-init/management-vm/meta-data \
    ~/vms/cloud-init/management-vm/network-config
----
. Create a pool to store the VM images
+
[source,bash]
----
virsh pool-define-as management-pool dir --target /var/lib/libvirt/management-pool
virsh pool-build management-pool
virsh pool-start management-pool
virsh pool-autostart management-pool
----
. Upload the VM image and resize it to at least 100G
+
[source,bash]
----
virsh vol-create-as --pool management-pool --name management-vm.qcow2 --capacity 100G --format qcow2
virsh vol-upload --pool management-pool management-vm.qcow2 /vms/images/management-vm-x86_64.qcow2
----
. Create the management network.
+
Copy the isolated.xml file from `metal-provision` and update the values to something that makes sense for your local environment.
ansible localhost -e @roles/node_images_hypervisor/defaults/main.yml -c local -m template -a "src=roles/node_images_hypervisor/templates/bootstrap/isolated.xml.j2 dest=isolated.xml"

+
[source,bash]
----
virsh net-create /vms/isolated.xml
----
. Boot the VM.
+
Copy the domain.xml file from `metal-provision` and update the memory and cpu values to something that will work with your local environment.
+
Example:
+
[source,xml]
----
  <memory unit='MiB'>4096</memory>
  <vcpu>2</vcpu>
----
Alternatively, use Ansible to generate the file from the template:
+
[source,bash]
----
ansible localhost -e @roles/node_images_hypervisor/defaults/main.yml -c local -m template -a "src=roles/node_images_hypervisor/templates/bootstrap/domain.xml.j2 dest=domain.xml"
----
+
Boot:
+
[source,bash]
----
virsh create /vms/domain.xml
----
. View the VM's console
+
[source,bash]
----
virsh console management-vm
----
. Login to the VM
+
[source,bash]
----
ssh root@192.168.0.2
----
