---
antora:
  extensions:
  - require: '@antora/lunr-extension'
site:
  title: Fawkes Project
  start_page: fawkes::index.adoc
content:
  sources:
  - url: https://github.com/Cray-HPE/docs-fawkes.git
    branches: main
    tags: v@({1..9})*({0..9}).+({0..9}).x
runtime:
  fetch: true
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://github.com/Cray-HPE/antora-ui/releases/download/1.0.0/ui-bundle.zip
    snapshot: true
