antora:
  extensions:
  - require: '@antora/lunr-extension'
site:
  title: Fawkes
  start_page: fawkes::index.adoc
content:
  sources:
  - url: ./..
    start_path: docs
    branches: main
    tags: v@({1..9})*({0..9}).+({0..9}).x
runtime:
  fetch: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
