= Node Deployment
:toc:
:toclevels: 3

This section of the guide will walk the user through deploying bare-metal nodes.

== Hypervisor Deployment

Deploying hypervisor nodes.

=== Deployment

Booting hypervisor nodes.

. Set credentials for RedFish
+
[source,bash]
----
cp /vms/assets/fawkes-*/gru.yml /etc/gru.yml
vi /etc/gru.yml
----

* Replace the `username:` and `password:` values with ones that correspond to the RedFish endpoints on the cluster.
* Set `insecure: true` if SSL is not configured with a trusted certificate on the RedFish endpoints.
. Boot the hypervisor nodes
+
[source,bash]
----
conman -q | grep ncn-h | gru -c /etc/gru.yml chassis boot http --now
----
. Each node should boot over HTTP and pull media.
. Manually wipe and install each node over the console.
* Connect to the node(s)
+
[source,bash]
----
ssh ncn-h002
----
// TODO: Fix the passwords, only the first hypervisor should prompt the user. The rest should not prompt if the user logs in with SSH.
* It'll ask you to set a password, the default password is blank.
* Wipe the node.
+
[source,bash]
----
crucible storage wipe -y
----
* Install the node.
+
[source,bash]
----
crucible install
----
* Reboot
+
[source,bash]
----
reboot
----
. Move onto the next hypervisor.


[NOTE]
====
After the hypervisor reboots, if no IP is set you may have to run the following.
[source,bash]
----
crucible network interface --dhcp mgmt0
----
This is a bug in the NetworkManager configuration and setup during the hypervisor install.
====

== Inventory

. Create an inventory file
+
[source,bash]
----
cat << EOF > /etc/ansible/inventory
[hypervisor]
hypervisor.local
$(conman -q | grep ncn | sed -s 's/-mgmt//')

[storage]
$(conman -q | grep ncn-s | sed -s 's/-mgmt//')
EOF
----

. Trust all deployed machines.
+
[source,bash]
----
for host in $(conman -q | grep -oP 'ncn-\w\d+'); do ssh-keyscan -H $host >> ~/.ssh/known_hosts 2>/dev/null; done
----

== Provision

Provision the hypervisor nodes.

. Provision the hypervisors.
+
[source,bash]
----
/opt/cray/ansible/bin/ansible-playbook \
    -i /etc/ansible/inventory \
    /srv/cray/metal-provision/hypervisor.yml
----
+
[WARNING]
====
If the note from the <<Inventory>> section was followed, Ansible will hang while setting up VLANs. When it hangs, login
to each node and run
[source,bash]
----
systemctl restart NetworkManager
nmcli device reapply mgmt0
----

====

== Storage

// TODO: Placeholder.
