= Management VM
:toc:
:toclevels: 3

WARNING: At this time, a new SSH key should be generated on the hypervisor to enable logging in. Run the xref:iso-installation.adoc#ssh-keys[SSH Key(s)] segment from within the hypervisor *before proceeding*.

. Start the management VM, provide the external IP address and DNS for remotely logging into the VM.
+
NOTE: See `--help` for optional parameters.
+
[source,bash]
----
crucible vm start --ip-address "10.100.254.5/24" --dns "16.110.135.51,16.110.135.52" --system-name "redbull"
----
.. The command will announce when SSH is ready.
+
[source,bash]
----
Waiting for SSH to become available.............................................
Management VM is online.
Login to the management-vm externally with:

ssh 10.100.254.5

Done.
----
.. For insight into the VM's launch, view its console in another terminal.
+
NOTE: Leave the console by pressing the escape character `^]` (kbd:[CTRL] + kbd:[]]).
+
[source,bash]
----
virsh console management-vm
----
. Once the node is up and cloud-init has printed a message indicating it has finished, open a new window and SSH to the
management-vm from the trusted workstation.
+
[source,bash]
----
ssh root@10.100.254.5
----
. Run the `bootserver` Ansible role.
+
[source,bash]
----
source /opt/cray/ansible/bin/activate
ansible-playbook /srv/cray/metal-provision/bootserver.yml
----
. Upload artifacts to nexus.
+
[source,bash]
----
/srv/cray/metal-provision/scripts/nexus/setup-nexus.sh -r /vms/assets/images -u os-images
----
+
[example]
The Nexus GUI may be accessed at http://my-servers-dns-name/nexus. The default username and password are `admin:admin123`.
. Proceed to the xref:gitea.adoc[] setup guide.
