= USB Creation
:toc:
:toclevels: 2

This guide walks the user through setting up a bootable USB for bootstrapping the Fawkes cluster.

NOTE: Users can also remotely mount the ISO using a BMC, but at this time a guide for doing so does not exist.

== Downloading

The Fawkes tarball needs to be downloaded.

NOTE: For the time being, the artifacts are downloaded individually and from a private mirror.
In the near future these will be available in a single artifact from a public mirror.

=== Prerequisites

The following prerequisites are necessary for completing this guide.

* `curl`

NOTE: Windows users can download link:https://curl.se/windows/[`curl` for Windows].

=== Downloading the Fawkes tarball

Fawkes is only available from a private mirror at this time.

. Download the latest, stable Hypervisor ISO
+
NOTE: At this time the ISO is only available for users that have credentials to the Artifactory instance.
+
.. Set Credentials
+
[source,bash]
----
ARTIFACTORY_USER
----
+
[source,bash]
----
ARTIFACTORY_TOKEN
----
+
[source,bash]
----
ARCH=x86_64
STREAM=stable
----
. Download the latest, stable Fawkes ISO
+
NOTE: To use a proxy, add `--proxy http://example.com:443` to each `curl` call.
+
[source,bash]
----
curl -C - -o fawkes-live-${ARCH}.iso "https://$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN@artifactory.algol60.net/artifactory/csm-images/${STREAM}/fawkes-live/\\[RELEASE\\]/fawkes-live-\\[RELEASE\\]-${ARCH}.iso"
----
. Download the latest, stable Hypervisor ISO
+
[source,bash]
----
curl -C - -o hypervisor-${ARCH}.iso "https://$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN@artifactory.algol60.net/artifactory/csm-images/${STREAM}/hypervisor/\\[RELEASE\\]/hypervisor-\\[RELEASE\\]-${ARCH}.iso"
----
. Download the latest, stable Management VM
+
[source,bash]
----
curl -C - -o management-vm-${ARCH}.qcow2 "https://$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN@artifactory.algol60.net/artifactory/csm-images/${STREAM}/management-vm/\\[RELEASE\\]/management-vm-\\[RELEASE\\]-${ARCH}.qcow2"
----
. Download the latest, stable Kubernetes VM
+
[source,bash]
----
curl -C - -o kubernetes-vm-${ARCH}.qcow2 "https://$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN@artifactory.algol60.net/artifactory/csm-images/${STREAM}/kubernetes-vm/\\[RELEASE\\]/kubernetes-vm-\\[RELEASE\\]-${ARCH}.qcow2"
----

== Creating the USB

This segment will walk the user through creating the USB with the downloaded tarball.

=== Linux

The Linux method will enable persistence as well as data storage for bringing artifacts into the booted LiveCD.

==== Prerequisites

Prerequisites for creating the USB from a Linux box.

* `blkid`
* `dd`
* `mktemp`
* `parted`
* `sgdisk`

==== Steps

. Download the `write-livecd.sh` script
+
[source,bash]
----
curl -s https://raw.githubusercontent.com/Cray-HPE/crucible/main/crucible/scripts/write-livecd.sh -O
set +x write-livecd.sh
----
. Find the USB to use.
+
NOTE: The target device does not need to be wiped.
. Invoke the script, optionally passing a different size (in megabytes) for the copy-on-write persistent partition.
+
[source,bash]
----
# usage: [DEVICE] [ISO] [SIZE OF COW]
sudo ./write-livecd.sh /dev/sdX ./fawkes-live-${ARCH}.iso 50000
----
. Mount the USB and copy over our downloaded artifacts.
+
[source,bash]
----
sudo mkdir -p /mnt
sudo mount -L data /mnt
sudo mkdir -p /mnt/images
sudo cp -p *.iso *.qcow2 /mnt/images/
sudo umount /mnt
----
. Eject the USB and plug it into the server for deployment.

=== MacOS and Windows

Creating a USB from MacOS and Windows is feasible using the help of a few third-party tools.

CAUTION: The MacOS and Windows method will not enable persistence on the drive.

==== Prerequisites

This guide suggests the following third-party tools for USB creation.

- link:https://etcher.balena.io/[belanaEtcher]

==== Steps

The following steps will create a bootable USB from a MacOS or Windows machine.

NOTE: `dd` can also be used for macOS users.

. Open belanaEtcher
. Select the ISO file, the USB stick, and click Flash
. Eject the USB and insert it into the server
