name: Publish Docs to Github Pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted-small
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Antora and the Antora Lunr Extension
      run: npm i antora @antora/lunr-extension

    - name: Generate Site
      run: npx antora docs-site/antora-playbook.yml
      
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/site