name: Publish Docs to Github Pages
on:
  push:
    branches: [main]
jobs:
  build:
    environment:
      name: github-pages
      url: https://cray-hpe.github.io/docs-fawkes
    runs-on: self-hosted-small
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Antora and the Antora Lunr Extension
      run: npm i antora @antora/lunr-extension

    - name: Generate Site
      working-directory: ./docs-site
      env:
        GIT_CREDENTIALS: https://${{ secrets.GITHUB_TOKEN }}@github.com
      run: npx antora antora-playbook.yml

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.9
      with:
        path: docs-site/build/site

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2